name: WorldEditPotato
main: WorldEditor\WorldEditor
version: INDEV_b1
api: 2.0.0
author: HuaYoyu
website: "https://github.com/Yoyu666/WorldEditPotato"
commands:
 toggleeditwand:
  description: 
  usage: "/toggleeditwand"
  permission: worldeditor.command
 /cut:
  description: Cuts the currently selected region.
  usage: "//cut"
  permission: worldeditor.command
 /copy:
  description: Copies the currently selected region. Be aware that it stores your position relative to the selection when copying.
  usage: "//copy"
  permission: worldeditor.command
 /paste:
  description: Pastes the clipboard.
  usage: "//paste"
  permission: worldeditor.command
 /sphere:
  description: make a potato.
  usage: "//sphere <block> <radius>"
  permission: worldeditor.command
 /hsphere:
  description:  make a potato with no have insde block.
  usage: "//hsphere <block> <radius>"
  permission: worldeditor.command
 /desel:
  description: Deselects the current selection.
  usage: "//desel"
  permission: worldeditor.command
 /limit:
  description: 
  usage: "//limit <limit>"
  permission: worldeditor.command
 /pos1:
  description: Set selection position #1 to the block above the one that you are standing on.
  usage: "//pos1"
  permission: worldeditor.command
 /pos2:
  description: Set selection position #2 to the block above the one that you are standing on.
  usage: "//pos2"
  permission: worldeditor.command
 /set:
  description: Set all blocks inside the selection region to a specified block(s).
  usage: "//set <blockID>"
  permission: worldeditor.command
 /replace:
  description: 
  usage: "//replace <fromBlock> <toBlock>"
  permission: worldeditor.command
 /help:
  description: to see all WD command.
  usage: "//help"
  permission: worldeditor.command
 /wand:
  description: 
  usage: "//wand"
  permission: worldeditor.command
 /undo:
  description: 
  usage: "//undo"
  permission: worldeditor.command
 /tree:
  description: 
  usage: "//tree <size>"
  permission: worldeditor.command
 /flower:
  description: 
  usage: "//flower <size>"
  permission: worldeditor.command
permissions:
    worldeditor:
        default: op
        description: "All the permissions to use the World Editor"
        children:
            worldeditor.command:
                default: op
                description: "Allow the usage of the WorldEditor command"
